Lps 145373 1 14
liferay-core-infra/liferay-portal pull request #200
Opened 2022-01-14 09:05 UTC by slnn

Hi @dantewang @tinatain

This pull aims to make the integration test export data for SampleSQLBuilder use.

Other changes on SampleSQLBuilder are on the way.

Thanks
Lily

2022-01-14 09:05 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-01-17 06:04 UTC, dantewang commented on modules/test/company-sample-data-generation-test/src/testIntegration/java/com/liferay/company/sample/data/generation/test/CompanySampleDataGenerationTest.java
> +@DataGuard(scope = DataGuard.Scope.NONE)
@slnn We want this scope to be "CLASS" on CI. Please don't change it. When running it locally we can manually change it or automate the changing using other ways.

2022-01-17 08:33 UTC, dantewang requested changes

2022-01-17 08:34 UTC, dantewang commented
@slnn @yuhai Please see my comments and modify the pull. Thanks!

2022-01-25 11:04 UTC, tinatian commented
@slnn I am going to close the pull based on @dantewang 's comment https://github.com/liferay-core-infra/liferay-portal/pull/200#issuecomment-1014262777

2022-01-25 11:04 UTC, tinatian commented
ci:close

2022-01-25 11:04 UTC, closed without merging