[Static references] LPS-182376 Remove static references in modules site-navigation, social and wiki
liferay-core-infra/liferay-portal pull request #4349
Opened 2023-04-24 16:28 UTC by RenanUmV

2023-04-24 16:28 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-04-24 16:37 UTC, RenanUmV commented
ci:test:wiki

2023-04-24 16:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>wiki</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/632/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/632/jenkins-report.html">here</a>.</b></p>

2023-04-24 16:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/10858/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10858/jenkins-report.html">here</a>.</b></p>

2023-04-24 19:35 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:wiki - 14 out of 40 jobs passed in 2 hours 42 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/4476">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1257401_632</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/179817cff6beb2b2a30309263dc98a7f2828ee70">179817cff6beb2b2a30309263dc98a7f2828ee70</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b2878f30f0010f5351535df066fbefa6958e35a4">b2878f30f0010f5351535df066fbefa6958e35a4</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2278558961">EE Development Acceptance (master) - 4475 - 2023-04-24[04:35:57]</a></p><details><summary><strong>ci:test:wiki - 14 out of 40 jobs PASSED</strong></summary><div><h4>26 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/632/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/181856/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/186106/"><strike>functional-tomcat90-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/545526/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/186763/"><strike>functional-tomcat90-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/191806/"><strike>functional-tomcat90-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/193423/"><strike>functional-tomcat90-mysql57-jdk8/0/4</strike></a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/196840/"><strike>functional-tomcat90-mysql57-jdk8/0/5</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/589980/"><strike>functional-tomcat90-mysql57-jdk8/0/6</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/90645/"><strike>functional-tomcat90-mysql57-jdk8/0/7</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/494240/"><strike>functional-tomcat90-mysql57-jdk8/0/8</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/494239/"><strike>functional-tomcat90-mysql57-jdk8/0/9</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/486096/"><strike>functional-tomcat90-mysql57-jdk8/0/10</strike></a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/201446/"><strike>functional-tomcat90-mysql57-jdk8/0/11</strike></a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/201134/"><strike>functional-tomcat90-mysql57-jdk8/0/12</strike></a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/171749/"><strike>functional-tomcat90-mysql57-jdk8/0/13</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/504371/"><strike>functional-tomcat90-mysql57-jdk8/0/14</strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/198286/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/193345/"><strike>functional-tomcat90-mysql57-jdk8/0/16</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/486098/"><strike>functional-tomcat90-mysql57-jdk8/0/17</strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/201822/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/503058/"><strike>functional-tomcat90-mysql57-jdk8/0/19</strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/201823/"><strike>functional-tomcat90-mysql57-jdk8/0/20</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/460783/"><strike>functional-tomcat90-mysql57-jdk8/0/21</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/355308/"><strike>functional-tomcat90-mysql57-jdk8/0/22</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/90647/"><strike>functional-tomcat90-mysql57-jdk8/0/23</strike></a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/192945/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/494243/"><strike>modules-integration-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/504374/"><strike>modules-integration-mysql57-jdk8/0/1</strike></a></li></ul></li><li>modules-semantic-versioning-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/65386/"><strike>modules-semantic-versioning-jdk8/0/0</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/537118/">modules-semantic-versioning-jdk8/0/1</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205646/">modules-semantic-versioning-jdk8/0/2</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/183462/">modules-semantic-versioning-jdk8/0/3</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/191805/">modules-semantic-versioning-jdk8/0/4</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/460781/">modules-semantic-versioning-jdk8/0/5</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/198284/">modules-semantic-versioning-jdk8/0/6</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454510/">modules-semantic-versioning-jdk8/0/7</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454509/">modules-semantic-versioning-jdk8/0/8</a></li></ul></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/18610 [...]

2023-04-24 19:47 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/632/">test-portal-acceptance-pullrequest(master)#632</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/632/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>wiki<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-core-infra/liferay-portal/pull/4349">liferay-core-infra#4349</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2278909540">[master] ci:test:wiki - RenanUmV &gt; liferay-core-infra - PR#4349 - 2023-04-24[09:52:24]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/1243/">publish-testray-report#1243</a><br/></div></div>

2023-04-24 19:54 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 22 out of 28 jobs passed</h3><h3>:x: ci:test:relevant - 35 out of 76 jobs passed in 3 hours</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/4476">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1377401_10858</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/179817cff6beb2b2a30309263dc98a7f2828ee70">179817cff6beb2b2a30309263dc98a7f2828ee70</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b2878f30f0010f5351535df066fbefa6958e35a4">b2878f30f0010f5351535df066fbefa6958e35a4</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2278558961">EE Development Acceptance (master) - 4475 - 2023-04-24[04:35:57]</a></p><details><summary><strong>ci:test:stable - 22 out of 28 jobs PASSED</strong></summary><div><h4>6 Failed Jobs:</h4><ul><li>build-iw-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/355329/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/355340/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/590016/"><strike>functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</strike></a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/189386/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/201143/"><strike>functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/590014/"><strike>functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</strike></a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/193535/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/191816/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/486115/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/545541/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/460807/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/590012/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454529/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/181863/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/537139/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454528/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/65410/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/355414/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/183470/">modules-compile-jdk8/0/11</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/503084/"><strike>modules-integration-mysql57-jdk8_stable/0/0</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/565682/"><strike>modules-integration-mysql57-jdk8_stable/0/1</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/545550/"><strike>modules-integration-mysql57-jdk8_stable/0/2</strike></a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454533/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454535/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-mysql57-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/486122/">portal-license-smoke-mysql57-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/503081/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/90669/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/161541/">unit-jdk8_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>22 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 35 out of 76 jobs PASSED</strong></summary><div><h4>41 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/10858/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/355329/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/355340/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/90671/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/193433/"><strike>functional-smoke-tomcat90-db2115-jdk8/0/0</strike></a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205654/"><strike>functional-smoke-tomcat90-hypersonic20-jdk8/0/0</strike></a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/343504/"><strike>functional-smoke-tomcat90-mysql57-jdk11_open/0/0</strike></a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pul [...]

2023-04-24 20:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/10858/">test-portal-acceptance-pullrequest(master)#10858</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10858/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-core-infra/liferay-portal/pull/4349">liferay-core-infra#4349</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2279087319">[master] ci:test:relevant - RenanUmV &gt; liferay-core-infra - PR#4349 - 2023-04-24[09:53:05]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/24099/">publish-testray-report#24099</a><br/></div></div>

2023-04-24 21:14 UTC, Kvale1733 commented
@RenanUmV Regression found. Seems the portal is completely broken with these changes. There are a lot of startup errors.
[Log](https://gist.github.com/Kvale1733/0cbea95bde0c4e82d8d3cc2e9db531d1)

Most of the UI is broken and there is no response when clicking any  of it. The welcome page also shows "An unexpected system error occurred".

2023-04-26 22:07 UTC, rafaprax requested changes

2023-04-26 22:07 UTC, rafaprax commented on modules/apps/wiki/wiki-web/src/main/java/com/liferay/wiki/web/internal/display/context/DLMimeTypeDisplayContextUtil.java
> +		DLMimeTypeDisplayContextUtil._dlMimeTypeDisplayContextSnapshot.get();
Hey @RenanUmV, you do not need this field `_dlMimeTypeDisplayContext`. You just need to use the snapshot in the methods implementations.

Thx

2023-04-26 22:07 UTC, rafaprax commented on modules/apps/wiki/wiki-engine-input-editor-common/src/main/java/com/liferay/wiki/engine/input/editor/common/internal/util/WikiEngineInputEditorCommonComponentProvider.java
Hey @RenanUmV, now the field `_wikiEngineInputEditorCommonComponentProvider` is never initialized. By the way, you do not need this more. 

Thx

2023-04-26 22:07 UTC, rafaprax commented
Hey @RenanUmV, see my comments and resend the pr. Thx

2023-04-26 22:07 UTC, closed without merging