[Round 4 Method Reference Static]Lps 182411 1
liferay-core-infra/liferay-portal pull request #4362
Opened 2023-04-25 05:38 UTC by slnn

https://issues.liferay.com/browse/LPS-182411

2023-04-25 05:38 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-04-25 05:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/3316/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3316/jenkins-report.html">here</a>.</b></p>

2023-04-25 05:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/5419/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5419/jenkins-report.html">here</a>.</b></p>

2023-04-25 05:41 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c63b172b86b183750b9e2044a4788245b37b2065">c63b172b86b183750b9e2044a4788245b37b2065</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/slnn/liferay-portal/tree/LPS-182411-1">LPS-182411-1</a><br/>Branch GIT ID: <a href="https://github.com/slnn/liferay-portal/commit/a38bdb0b2d3f1a88e27e4a4fac718d2532213a01">a38bdb0b2d3f1a88e27e4a4fac718d2532213a01</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/5419/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5419/jenkins-report.html">here</a>.</h5></details></html>

2023-04-25 05:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/5419/">test-portal-source-format#5419</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5419/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-core-infra/liferay-portal/pull/4362">liferay-core-infra#4362</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2279669146">[master] ci:test:sf - slnn &gt; liferay-core-infra - PR#4362 - 2023-04-24[22:38:36]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/20673/">publish-testray-report#20673</a><br/></div></div>

2023-04-25 06:54 UTC, dantewang requested changes

2023-04-25 06:54 UTC, dantewang commented on modules/dxp/apps/portal-search-tuning/portal-search-tuning-rankings-web/src/test/java/com/liferay/portal/search/tuning/rankings/web/internal/util/RankingResultUtilTest.java
> +			Mockito.mock(Snapshot.class);
@slnn Hmmm maybe I missed this thing in your previous change. Is it possible to NOT mock `Snapshot`? You can register the mocked "_documentBuilderFactory" or "_searchResultInterpreterProvider" using the bundle context, and expect that the snapshot can properly return them.

2023-04-25 06:56 UTC, dantewang commented
@slnn Please update the test and resend. Could you please also review your other merged changes to and send a follow-up PR to update the tests you previously modified? Thanks.

2023-04-25 06:56 UTC, dantewang commented
ci:stop

2023-04-25 07:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/3316/">test-portal-acceptance-pullrequest(master)#3316</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3316/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-core-infra/liferay-portal/pull/4362">liferay-core-infra#4362</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2279705510">[master] ci:test:relevant - slnn &gt; liferay-core-infra - PR#4362 - 2023-04-24[22:38:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/7524/">publish-testray-report#7524</a><br/></div></div>

2023-04-26 08:26 UTC, closed without merging

2023-04-26 08:51 UTC, slnn commented
Resend in https://github.com/liferay-core-infra/liferay-portal/pull/4383