[Remove Blocking usages]LPS-186857 document-library-service | DLSubscriptionSender
liferay-core-infra/liferay-portal pull request #4820
Opened 2023-06-21 00:55 UTC by W2jx

2023-06-21 00:55 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-06-21 00:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/6940/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6940/jenkins-report.html">here</a>.</b></p>

2023-06-21 00:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>startup</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/9991/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9991/jenkins-report.html">here</a>.</b></p>

2023-06-21 00:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/805/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/805/jenkins-report.html">here</a>.</b></p>

2023-06-21 00:58 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/12215837589ab542ccf89e0968a80e8ca026e8fe">12215837589ab542ccf89e0968a80e8ca026e8fe</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/W2jx/liferay-portal/tree/LPS-186857-6-21-1">LPS-186857-6-21-1</a><br/>Branch GIT ID: <a href="https://github.com/W2jx/liferay-portal/commit/82a211ee778174d0ea9d81ccaafc1dbf1b42b112">82a211ee778174d0ea9d81ccaafc1dbf1b42b112</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/805/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/805/jenkins-report.html">here</a>.</h5></details></html>

2023-06-21 00:59 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:startup - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/12215837589ab542ccf89e0968a80e8ca026e8fe">12215837589ab542ccf89e0968a80e8ca026e8fe</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e5341d48364c62e329d3c551ded58f3900e3c0b5">e5341d48364c62e329d3c551ded58f3900e3c0b5</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2354414877">EE Development Acceptance (master) - 4627 - 2023-06-19[00:35:16]</a></p><details><summary><strong>ci:test:startup - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/9991/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9991/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/9991/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>POSHI Validation Failure<pre> [parallel] 2 errors in Poshi Script syntax
 [parallel] 
 [parallel] 1. Unmatched opening boundary at:
 [parallel] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceAccountSupplierRole.testcase:80
 [parallel] 
 [parallel] 2. Unmatched opening boundary at:
 [parallel] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceAccountSupplierRole.testcase:80
 [parallel] [functional-smoke-startup-tomcat90-mysql57-jdk8] Retry creating a test class group in 5 seconds.
 [parallel] getRemoteGitRefs found 1 refs at git@cloud-10-0-0-37:liferay/com-liferay-osb-faro-private.git in 238 ms.
 [parallel] Executing commands: git ls-remote -h -t git@cloud-10-0-0-39:liferay/com-liferay-osb-faro-private.git cache-liferay-72b21174c2e3948bfab7622783daf8897b0b71c9-liferay-4d1f6d0d516e0639f8e129b402f0ce019cde710f
 [parallel] getRemoteGitRefs found 1 refs at git@cloud-10-0-0-38:liferay/com-liferay-osb-faro-private.git in 241 ms.
 [parallel] Executing commands: git ls-remote -h -t git@github-dev.cluster-1.lax.liferay.com:liferay/com-liferay-osb-faro-private.git cache-liferay-72b21174c2e3948bfab7622783daf8897b0b71c9-liferay-4d1f6d0d516e0639f8e129b402f0ce019cde710f
 [parallel] getRemoteGitRefs found 1 refs at git@cloud-10-0-0-39:liferay/com-liferay-osb-faro-private.git in 140 ms.
 [parallel] Executing commands: git ls-remote -h -t git@github-dev.cluster-2.lax.liferay.com:liferay/com-liferay-osb-faro-private.git cache-liferay-72b21174c2e3948bfab7622783daf8897b0b71c9-liferay-4d1f6d0d516e0639f8e129b402f0ce019cde710f
     [echo] Generating Jenkins report.
[beanshell] Jenkins reported generated in 62 ms
     [echo] Rsyncing Jenkins report.
[beanshell] Remote execution starting with 1 threads.
[beanshell] Executing commands: ssh -o NumberOfPasswordPrompts=0 test-1-26 'mkdir -p /opt/java/jenkins/userContent/jobs/test-portal-acceptance-pullrequest\(master\)/builds/9991/'
[beanshell] Average thread duration: 225ms
[beanshell] Busy slaves:0
[beanshell] Finished slaves:1
[beanshell] Target slaves:1
[beanshell] Total duration: 225
[beanshell] Remote execution completed in 225ms.
[beanshell] getRemoteGitRefs found 1 refs at git@github-dev.cluster-1.lax.liferay.com:liferay/com-liferay-osb-faro-private.git in 964 ms.
[beanshell] Executing commands: git ls-remote -h -t git@github-dev.cluster-3.lax.liferay.com:liferay/com-liferay-osb-faro-private.git cache-liferay-72b21174c2e3948bfab7622783daf8897b0b71c9-liferay-4d1f6d0d516e0639f8e129b402f0ce019cde710f
[beanshell] getRemoteGitRefs found 1 refs at git@github-dev.cluster-2.lax.liferay.com:liferay/com-liferay-osb-faro-private.git in 1 second.
[beanshell] Executing commands: git ls-remote -h -t git@github-dev.cluster-4.lax.liferay.com:liferay/com-liferay-osb-faro-private.git cache-liferay-72b21174c2e3948bfab7622783daf8897b0b71c9-liferay-4d1f6d0d516e0639f8e129b402f0ce019cde710f
   [delete] Deleting: /opt/dev/projects/github/liferay-jenkins-ee/commands/20230620175912209
 [parallel] getRemoteGitRefs found 0 refs at git@github-dev.cluster-14.lax.liferay.com:liferay/liferay-portal.git in 9 seconds.
 [parallel] Executing commands: git ls-remote -h -t git@github-dev.cluster-5.lax.liferay.com:liferay/com-liferay-osb-faro-private.git cache-liferay-72b21174c2e3948bfab7622783daf8897b0b71c9-liferay-4d1f6d0d516e0639f8e129b402f0ce019cde710f
 [parallel] getRemoteGitRefs found 1 refs at git@github-dev.cluster-3.lax.liferay.com:liferay/com-liferay-osb-faro-private.git in 1 second.
 [parallel] Executing commands: git ls-remote -h -t git@github-dev.cluster-6.lax.liferay.com:liferay/com-liferay-osb-faro-private.git cache-liferay-72b21174c2e3948bfab7622783daf8897b0b71c9-liferay-4d1f6d0d516e0639f8e129b402f0ce019cde710f
 [parallel] getRemoteGitRefs found 1 refs at git@github-dev.cluster-4.lax.liferay.com:liferay/com-liferay-osb-faro-private.git in 1 second.
 [parallel] Executing commands: git ls-remote -h -t git@github-dev.cluster-7.lax.liferay.com:liferay/com-liferay-osb-faro-private.git cache-liferay-72b21174c2e3948bfab7622783daf8897b0b71c9-liferay-4d1f6d0d516e0639f8e129b402f0ce019cde710f
 [parallel] getRemoteGitRefs found 0 refs at git@github-dev.cluster-10.lax.liferay.com:liferay/liferay-portal.git in 14 seconds.
 [parallel] Executing commands: git ls-remote -h -t git@github-dev.cluster-8.lax.liferay.com:liferay/com-liferay-osb-faro-private.git cache-liferay-72b21174c2e3948bfab7622783daf8897b0b71c9-liferay-4d1f6d0d516e0639f8e129b402f0ce019cde710f
 [parallel] getRemoteGitRefs found 1 refs at git@github-dev.cluster-6.lax.liferay.com:liferay/com-liferay-osb-faro-private.git in 1 second.
 [parallel] Executing commands: git ls-remote -h -t git@github-dev.cluster-9.lax.liferay.com:liferay/com-liferay-osb-faro-private.git cache-liferay-72b21174c2e3948bfab7622783daf8897b0b71c9-liferay-4d1f6d0d516e0639f8e129b402f0ce019cde710f
 [parallel] getRemoteGitRefs found 0 refs at git@github-dev.cluster-15.lax.liferay.com:liferay/liferay-portal.git in 8 seconds.
 [parallel] Executing commands: git ls-remote -h -t git@github-dev.cluster-10.lax.liferay.com:liferay/com-liferay-osb-faro-private.git cache-liferay-72b21174c2e3948bfab7622783daf8897b0b71c9-liferay-4d1f6d0d516e0639f8e129b402f0ce019cde710f
 [parallel] getRemoteGitRefs found 1 refs at git@github-dev.cluster-5.lax.liferay.com:liferay/com-liferay-osb-faro-private.git in 1 second.
 [parallel] Executing commands: git ls-remote -h -t git@github-dev.cluster-11.lax.liferay.com:liferay/com-liferay-osb-faro-private.git cache-liferay-72b21174c2e3948bfab7622783daf8897b0b71c9-liferay-4d1f6d0d516e0639f8e129b402f0ce019cde710f
 [parallel] getRemoteGitRefs found 1 refs at git@github-dev.cluster-8.lax.liferay.com:liferay/com-liferay-osb-faro-private.git in 1 second.
 [parallel] Executing commands: git ls-remote -h -t git@github-dev.cluster-12.lax.liferay.com:liferay/com-liferay-osb-faro-private.git cache-liferay-72b21174c2e3948bfab7622783daf8897b0b71c9-liferay-4d1f6d0d516e0639f8e129b402f0ce019cde710f
 [parallel] getRemoteGitRefs found 1 refs at git@github-dev.cluster-7.lax.liferay.com:liferay/com-liferay-osb-faro-private.git in 1 second.
 [parallel] Executing commands: git ls-remote -h -t git@github-dev.cluster-13.lax.liferay.com:liferay/com-liferay-osb-faro-private.git cache-liferay-72b21174c2e3948bfab7622783daf8897b0b71c9-liferay-4d1f6d0d516e0639f8e129b402f0ce019cde710f
 [parallel] ge [...]

2023-06-21 01:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/805/">test-portal-source-format#805</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/805/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-core-infra/liferay-portal/pull/4820">liferay-core-infra#4820</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2356423036">[master] ci:test:sf - W2jx &gt; liferay-core-infra - PR#4820 - 2023-06-20[17:55:43]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/3111/">publish-testray-report#3111</a><br/></div></div>

2023-06-21 05:36 UTC, W2jx commented
ci:test:startup

2023-06-21 05:37 UTC, W2jx commented
ci:test:relevant

2023-06-21 05:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>startup</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/10003/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10003/jenkins-report.html">here</a>.</b></p>

2023-06-21 06:46 UTC, zhangyan0701 commented
ci:test:relevant

2023-06-21 06:46 UTC, zhangyan0701 commented
ci:test:document

2023-06-21 07:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>document</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/3531/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3531/jenkins-report.html">here</a>.</b></p>

2023-06-21 07:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/5546/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5546/jenkins-report.html">here</a>.</b></p>

2023-06-21 08:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/10003/">test-portal-acceptance-pullrequest(master)#10003</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10003/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>startup<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-core-infra/liferay-portal/pull/4820">liferay-core-infra#4820</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2356705673">[master] ci:test:startup - W2jx &gt; liferay-core-infra - PR#4820 - 2023-06-20[22:37:02]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/22851/">publish-testray-report#22851</a><br/></div></div>

2023-06-21 09:52 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 32 out of 32 jobs passed</h3><h3>:x: ci:test:relevant - 119 out of 128 jobs passed in 2 hours 40 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/63ace052bdf233ff5ca6ff7129bb2f9147344758">63ace052bdf233ff5ca6ff7129bb2f9147344758</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e5341d48364c62e329d3c551ded58f3900e3c0b5">e5341d48364c62e329d3c551ded58f3900e3c0b5</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2354414877">EE Development Acceptance (master) - 4627 - 2023-06-19[00:35:16]</a></p><details><summary><strong>ci:test:stable - 32 out of 32 jobs PASSED</strong></summary><details><summary><strong>32 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 119 out of 128 jobs PASSED</strong></summary><div><h4>9 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/5546/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/628220/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/596183/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/190725/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/665537/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/164801/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/613239/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/665541/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/441203/">functional-smoke-tomcat90-oracle193-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/532923/">functional-smoke-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2019-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/532920/">functional-smoke-tomcat90-sqlserver2019-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/441199/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/692004/"><strike>functional-smoke-wildfly180-mariadb106-jdk8/0/0</strike></a></li></ul></li><li>functional-tomcat90-mysql57-chrome100-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/164803/">functional-tomcat90-mysql57-chrome100-jdk8/0/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/569887/">functional-tomcat90-mysql57-chrome100-jdk8/0/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/628224/">functional-tomcat90-mysql57-chrome100-jdk8/0/2</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/190721/">functional-tomcat90-mysql57-chrome100-jdk8/0/3</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/596180/">functional-tomcat90-mysql57-chrome100-jdk8/0/4</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/190720/">functional-tomcat90-mysql57-chrome100-jdk8/0/5</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/597595/">functional-tomcat90-mysql57-chrome100-jdk8/0/6</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/613242/">functional-tomcat90-mysql57-chrome100-jdk8/0/7</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/665538/">functional-tomcat90-mysql57-chrome100-jdk8/0/8</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/441194/">functional-tomcat90-mysql57-chrome100-jdk8/1/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/224242/">functional-tomcat90-mysql57-chrome100-jdk8/1/1</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/222546/">functional-tomcat90-mysql57-chrome100-jdk8/1/2</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/692006/">functional-tomcat90-mysql57-chrome100-jdk8/1/3</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/447753/">functional-tomcat90-mysql57-chrome100-jdk8/1/4</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/532921/">functional-tomcat90-mysql57-chrome100-jdk8/1/5</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/447754/">functional-tomcat90-mysql57-chrome100-jdk8/1/6</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/597591/">functional-tomcat90-mysql57-chrome100-jdk8/1/7</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/573012/">functional-tomcat90-mysql57-chrome100-jdk8/1/8</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/447755/">functional-tomcat90-mysql57-chrome100-jdk8/1/9</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/597590/">functional-tomcat90-mysql57-chrome100-jdk8/1/10</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/573011/">functional-tomcat90-mysql57-chrome100-jdk8/1/11</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/613238/">functional-tomcat90-mysql57-chrome100-jdk8/1/12</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/628221/">functional-tomcat90-mysql57-chrome100-jdk8/1/13</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/569885/">functional-tomcat90-mysql57-chrome100-jdk8/1/14</a></li><li><a href="https://test-1-27.liferay.com/job/t [...]

2023-06-21 09:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/5546/">test-portal-acceptance-pullrequest(master)#5546</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5546/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-core-infra/liferay-portal/pull/4820">liferay-core-infra#4820</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2356726451">[master] ci:test:relevant - W2jx &gt; liferay-core-infra - PR#4820 - 2023-06-21[00:12:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/11609/">publish-testray-report#11609</a><br/></div></div>

2023-06-21 10:11 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:document - 163 out of 180 jobs passed in 3 hours</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/63ace052bdf233ff5ca6ff7129bb2f9147344758">63ace052bdf233ff5ca6ff7129bb2f9147344758</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e5341d48364c62e329d3c551ded58f3900e3c0b5">e5341d48364c62e329d3c551ded58f3900e3c0b5</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2354414877">EE Development Acceptance (master) - 4627 - 2023-06-19[00:35:16]</a></p><details><summary><strong>ci:test:document - 163 out of 180 jobs PASSED</strong></summary><div><h4>17 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/3531/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/597557/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/628188/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/572984/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/628187/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/665502/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/572985/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/164763/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/691972/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/543376/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/628189/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/691973/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/441147/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/190679/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/596138/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/569852/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/532890/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/597550/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/569856/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/596144/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/532896/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/596145/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/544356/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/532898/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/569859/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/596147/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/447713/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/226909/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/210005/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/596139/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/190680/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/665498/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/665499/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/532891/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/225545/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/569853/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/613210/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/447719/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/691976/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/665505/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/222533/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/214964/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/224231/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/441153/"><strike>functional-tomcat90-mysql57-jdk8/1/17</strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/233149/">functional-tomcat90-mysql57-jdk8/1/18</a></ [...]

2023-06-21 10:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/3531/">test-portal-acceptance-pullrequest(master)#3531</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3531/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>document<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-core-infra/liferay-portal/pull/4820">liferay-core-infra#4820</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2356760692">[master] ci:test:document - W2jx &gt; liferay-core-infra - PR#4820 - 2023-06-21[00:10:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/6509/">publish-testray-report#6509</a><br/></div></div>

2023-06-23 06:50 UTC, W2jx commented
no conflicts(6/23 14.49)

2023-06-26 06:54 UTC, dantewang requested changes
cc @JanisZhang @LisztLiszt @slnn

2023-06-26 06:54 UTC, dantewang commented on modules/apps/document-library/document-library-service/src/main/java/com/liferay/document/library/internal/util/DLSubscriptionSender.java
> +				"(model.class.name=" + DLFolder.class.getName() + ")", false);
@W2jx This class is in module, and it's only used by one component. Normally we can reference the model resource permission and pass via constructor. However, considering SubscriptionSender may be serialized, please try to use `Snapshot` instead.

2023-06-26 06:54 UTC, closed without merging