LPS-190994
liferay-core-infra/liferay-portal pull request #5525
Opened 2023-09-11 13:38 UTC by marianoalvarosaiz

2023-09-11 13:38 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-09-11 13:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/7293/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7293/jenkins-report.html">here</a>.</b></p>

2023-09-11 13:42 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d7210e871573904fcf486a55af02f57f5a2d2c74">d7210e871573904fcf486a55af02f57f5a2d2c74</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/marianoalvarosaiz/liferay-portal/tree/LPS-190994">LPS-190994</a><br/>Branch GIT ID: <a href="https://github.com/marianoalvarosaiz/liferay-portal/commit/742f5c08e84ed430fb440b9cc158ad7cc363d0ad">742f5c08e84ed430fb440b9cc158ad7cc363d0ad</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7293/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7293/jenkins-report.html">here</a>.</h5></details></html>

2023-09-11 13:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7293/">test-portal-source-format#7293</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7293/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-core-infra/liferay-portal/pull/5525">liferay-core-infra#5525</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2422092133">[master] ci:test:sf - marianoalvarosaiz &gt; liferay-core-infra - PR#5525 - 2023-09-11[06:38:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/27125/">publish-testray-report#27125</a><br/></div></div>

2023-09-11 14:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/1985/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1985/jenkins-report.html">here</a>.</b></p>

2023-09-11 20:43 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 30 out of 30 jobs passed</h3><h3>:x: ci:test:relevant - 564 out of 635 jobs passed in 5 hours 33 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d7210e871573904fcf486a55af02f57f5a2d2c74">d7210e871573904fcf486a55af02f57f5a2d2c74</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bb2e86dc48c9154cb076f1a44e166c21c8f26df0">bb2e86dc48c9154cb076f1a44e166c21c8f26df0</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2420487470">EE Development Acceptance (master) - 6 - 2023-09-07[08:40:49]</a></p><details><summary><strong>ci:test:stable - 30 out of 30 jobs PASSED</strong></summary><details><summary><strong>30 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 564 out of 635 jobs PASSED</strong></summary><div><h4>71 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/1985/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/678563/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/231582/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/259990/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/707620/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/293763/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/265417/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/573672/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/644293/">functional-smoke-tomcat90-oracle193-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334550/">functional-smoke-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql153-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/663789/"><strike>functional-smoke-tomcat90-postgresql153-jdk8/0/0</strike></a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2019-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/663711/">functional-smoke-tomcat90-sqlserver2019-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/281475/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/835829/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-chrome100-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/835832/">functional-tomcat90-mysql57-chrome100-jdk8/0/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/663779/">functional-tomcat90-mysql57-chrome100-jdk8/0/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/678567/">functional-tomcat90-mysql57-chrome100-jdk8/0/2</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/663780/">functional-tomcat90-mysql57-chrome100-jdk8/0/3</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/707615/">functional-tomcat90-mysql57-chrome100-jdk8/0/4</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/573677/">functional-tomcat90-mysql57-chrome100-jdk8/0/5</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/758927/">functional-tomcat90-mysql57-chrome100-jdk8/0/6</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/663778/">functional-tomcat90-mysql57-chrome100-jdk8/0/7</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/712664/"><strike>functional-tomcat90-mysql57-chrome100-jdk8/0/8</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/573678/"><strike>functional-tomcat90-mysql57-chrome100-jdk8/0/9</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/712650/"><strike>functional-tomcat90-mysql57-chrome100-jdk8/0/10</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/686697/">functional-tomcat90-mysql57-chrome100-jdk8/0/11</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/663765/">functional-tomcat90-mysql57-chrome100-jdk8/0/12</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/712652/">functional-tomcat90-mysql57-chrome100-jdk8/0/13</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/587855/">functional-tomcat90-mysql57-chrome100-jdk8/0/14</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/734877/">functional-tomcat90-mysql57-chrome100-jdk8/0/15</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/663766/">functional-tomcat90-mysql57-chrome100-jdk8/0/16</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/712654/">functional-tomcat90-mysql57-chrome100-jdk8/0/17</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/734876/">functional-tomcat90-mysql57-chrome100-jdk8/0/18</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/686698/">functional-tomcat90-mysql57-chrome100-jdk8/0/19</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/587853/">functional-tomcat90-mysql57-chrome100-jdk8/0/20</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/587852/">functional-tomcat90-mysql57-chrome100-jdk8/0/21</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(ma [...]

2023-09-11 21:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/1985/">test-portal-acceptance-pullrequest(master)#1985</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1985/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-core-infra/liferay-portal/pull/5525">liferay-core-infra#5525</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2422316902">[master] ci:test:relevant - marianoalvarosaiz &gt; liferay-core-infra - PR#5525 - 2023-09-11[07:39:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/27149/">publish-testray-report#27149</a><br/></div></div>

2023-09-12 05:47 UTC, dantewang requested changes
@marianoalvarosaiz Please see my comments. By the way, when I run the `SchedulerEnginerHelperTest`, I see such error message after the test finishes:

```
2023-09-12 13:31:22.458 INFO  [Arquillian-Connector-Thread][BundleStartStopLogger:71] STOPPED com.liferay.portal.scheduler.test_1.0.0 [1534]
2023-09-12 13:32:18.682 ERROR [MemoryQuartzSchedulerEngineInstance_Worker-1][MessageSenderJob:37] Unable to execute job
java.lang.IllegalStateException: Destination liferay/scheduler_dispatch is shutdown and cannot receive more messages
        at com.liferay.portal.messaging.internal.BaseAsyncDestination.send(BaseAsyncDestination.java:153) ~[?:?]
        at com.liferay.portal.messaging.internal.DefaultMessageBus.sendMessage(DefaultMessageBus.java:101) ~[?:?]
        at com.liferay.portal.scheduler.quartz.internal.job.MessageSenderJob._execute(MessageSenderJob.java:81) ~[bundleFile:?]
        at com.liferay.portal.scheduler.quartz.internal.job.MessageSenderJob.execute(MessageSenderJob.java:34) [bundleFile:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [bundleFile:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [bundleFile:?]
```

Could you double check?

2023-09-12 05:47 UTC, dantewang commented on modules/apps/portal-scheduler/portal-scheduler-test/src/testIntegration/java/com/liferay/portal/scheduler/internal/test/SchedulerEngineHelperTest.java
> +	private static class ExpectedLogs {
@marianoalvarosaiz All 4 usages of this inner class are using same `level` and `loggerClassName`. For now, no need to abstract it into an inner class. Please remove it, and directly pass the `String... expectedMessages` to `assertExpectedLogs()`.

2023-09-12 05:47 UTC, dantewang commented on portal-kernel/test/unit/com/liferay/portal/kernel/scheduler/TriggerConfigurationTest.java
> +				-1, TimeUnit.MINUTE);
@marianoalvarosaiz Based on the method name, it should be `0`.

2023-09-12 05:47 UTC, dantewang commented on modules/apps/portal-scheduler/portal-scheduler-test/src/testIntegration/java/com/liferay/portal/scheduler/internal/test/SchedulerEngineHelperTest.java
> +				final DefaultNoticeableFuture<FrameworkEvent>
@marianoalvarosaiz No need to declare `final` here, it can be implied as final because there's no other modification.

2023-09-12 08:02 UTC, closed without merging

2023-09-12 08:10 UTC, marianoalvarosaiz commented
@dantewang see https://github.com/liferay-core-infra/liferay-portal/pull/5533

Regarding the error message you mention I've tried like ten times to reproduce it and it always ends with no failure:

```
> Task :apps:portal-scheduler:portal-scheduler-test:testIntegration

com.liferay.portal.scheduler.internal.test.SchedulerEngineHelperTest > testJobIsNotScheduledIfCronExpressionIsBlank STARTED

com.liferay.portal.scheduler.internal.test.SchedulerEngineHelperTest > testJobIsNotScheduledIfCronExpressionIsBlank PASSED

com.liferay.portal.scheduler.internal.test.SchedulerEngineHelperTest > testJobIsNotScheduledIfIntervalIsZero STARTED

com.liferay.portal.scheduler.internal.test.SchedulerEngineHelperTest > testJobIsNotScheduledIfIntervalIsZero PASSED

com.liferay.portal.scheduler.internal.test.SchedulerEngineHelperTest > testJobIsScheduledIfCronExpressionIsNotBlank STARTED

com.liferay.portal.scheduler.internal.test.SchedulerEngineHelperTest > testJobIsScheduledIfCronExpressionIsNotBlank PASSED

com.liferay.portal.scheduler.internal.test.SchedulerEngineHelperTest > testJobIsScheduledIfIntervalGreaterThanZero STARTED

com.liferay.portal.scheduler.internal.test.SchedulerEngineHelperTest > testJobIsScheduledIfIntervalGreaterThanZero PASSED

com.liferay.portal.scheduler.internal.test.SchedulerEngineHelperTest > testSchedulerGetsActivatedAfterInvalidInterval STARTED

2023-09-12 08:01:37.463 INFO  [Refresh Thread: Equinox Container: 02ef115c-bc3a-4b6e-aaa5-a6358391167b][BundleStartStopLogger:71] STOPPED com.liferay.portal.scheduler_8.0.36 [166]
2023-09-12 08:01:37.545 INFO  [Refresh Thread: Equinox Container: 02ef115c-bc3a-4b6e-aaa5-a6358391167b][BundleStartStopLogger:68] STARTED com.liferay.portal.scheduler_8.0.36 [166]

> Task :apps:portal-scheduler:portal-scheduler-test:testIntegration

com.liferay.portal.scheduler.internal.test.SchedulerEngineHelperTest > testSchedulerGetsActivatedAfterInvalidInterval PASSED

com.liferay.portal.scheduler.internal.test.SchedulerEngineHelperTest > testSchedulerGetsActivatedAfterNullCronExpression STARTED

2023-09-12 08:01:41.359 INFO  [Refresh Thread: Equinox Container: 02ef115c-bc3a-4b6e-aaa5-a6358391167b][BundleStartStopLogger:71] STOPPED com.liferay.portal.scheduler_8.0.36 [166]
2023-09-12 08:01:41.464 INFO  [Refresh Thread: Equinox Container: 02ef115c-bc3a-4b6e-aaa5-a6358391167b][BundleStartStopLogger:68] STARTED com.liferay.portal.scheduler_8.0.36 [166]

> Task :apps:portal-scheduler:portal-scheduler-test:testIntegration


```com.liferay.portal.scheduler.internal.test.SchedulerEngineHelperTest > testSchedulerGetsActivatedAfterNullCronExpression PASSED

2023-09-12 08:01:48.052 INFO  [Arquillian-Connector-Thread][BundleStartStopLogger:71] STOPPED com.liferay.portal.scheduler.test_1.0.0 [1533]

> Task :apps:portal-scheduler:portal-scheduler-test:stopTestableTomcat


BUILD SUCCESSFUL in 4m 4s
11 actionable tasks: 9 executed, 2 up-to-date
```


Besides, CI also ends with no failure: https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/758933/consoleFull