LPD-2612 | master
liferay-core-infra/liferay-portal pull request #7116
Opened 2024-06-06 21:41 UTC by marcosapmf

Jira ticket: https://liferay.atlassian.net/browse/LPD-2612

2024-06-06 21:41 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-06-06 21:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/6014/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/6014/jenkins-report.html">here</a>.</b></p>

2024-06-06 21:44 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b61046a62524d158630dc3748c7eaa31cebd1836">b61046a62524d158630dc3748c7eaa31cebd1836</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/marcosapmf/liferay-portal/tree/LPD-2612-1">LPD-2612-1</a><br/>Branch GIT ID: <a href="https://github.com/marcosapmf/liferay-portal/commit/d25f473ce4ce1fa0b13b8e8e3cdba281d2941617">d25f473ce4ce1fa0b13b8e8e3cdba281d2941617</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/6014/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/6014/jenkins-report.html">here</a>.</h5></details></html>

2024-06-06 21:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/6014/">test-portal-source-format#6014</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/6014/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-core-infra/liferay-portal/pull/7116">liferay-core-infra#7116</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/11950226">[master] ci:test:sf - marcosapmf &gt; liferay-core-infra - PR#7116 - 2024-06-06[14:41:39]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>11950226<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/22266/">publish-testray-report#22266</a><br/></div></div>

2024-06-07 03:07 UTC, dantewang requested changes
@marcosapmf Please see my comments and resend, thanks!

2024-06-07 03:07 UTC, dantewang commented on modules/dxp/apps/analytics/analytics-reports-web/src/main/java/com/liferay/analytics/reports/web/internal/product/navigation/control/menu/AnalyticsReportsProductNavigationControlMenuEntry.java
> +		cacheBuilder.expireAfterAccess(10, TimeUnit.MINUTES);
@marcosapmf Currently the values in this cache will only be invalided due to this 10-minute expiration. So, if the permission gets changed, the change will only take effect after this cache proactively expire the previous result. If there's no proper way to invalidate cache values upon permission changes, please do not cache it.

2024-06-07 03:07 UTC, dantewang commented on modules/dxp/apps/analytics/analytics-reports-web/src/main/java/com/liferay/analytics/reports/web/internal/product/navigation/control/menu/AnalyticsReportsProductNavigationControlMenuEntry.java
> +import com.google.common.cache.Cache;
@marcosapmf Also, please avoid using Google Cache even if you can find a way to properly manage the result invalidation. Please use portal cache instead. With portal cache (based on Ehcache) we can easily review the hit/miss/other statistics, while with Google Cache we don't have any of those.

2024-06-07 03:07 UTC, closed without merging

2024-06-07 17:03 UTC, marcosapmf commented
Hi @dantewang,
thanks for reviewing.
I just resent another pull request removing cache layer: https://github.com/liferay-core-infra/liferay-portal/pull/7122
Thanks