[OrderByComparator] LPD 28067 Apply Singleton in module commerce-price-list-api
liferay-core-infra/liferay-portal pull request #7210
Opened 2024-07-02 20:54 UTC by Valmir-unicap

2024-07-02 20:54 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-07-02 21:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-1.liferay.com/job/test-portal-source-format/3931/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/3931/jenkins-report.html">here</a>.</b></p>

2024-07-02 21:37 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 43 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6018936ec6dbb6d685a971a4336612219224bfd4">6018936ec6dbb6d685a971a4336612219224bfd4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Valmir-unicap/liferay-portal/tree/LPD-28067">LPD-28067</a><br/>Branch GIT ID: <a href="https://github.com/Valmir-unicap/liferay-portal/commit/a3637fdba94985c8ef2a5c0bc0408c9ee0c67cf5">a3637fdba94985c8ef2a5c0bc0408c9ee0c67cf5</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-1.liferay.com/job/test-portal-source-format/3931/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/3931/jenkins-report.html">here</a>.</h5></details></html>

2024-07-02 21:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-1.liferay.com/job/test-portal-source-format/3931/">test-portal-source-format#3931</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/3931/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-core-infra/liferay-portal/pull/7210">liferay-core-infra#7210</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/29725587">[master] ci:test:sf - Valmir-unicap &gt; liferay-core-infra - PR#7210 - 2024-07-02[13:54:57]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>29725587<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-1.liferay.com/job/publish-testray-report/25955/">publish-testray-report#25955</a><br/></div></div>

2024-07-02 22:02 UTC, Valmir-unicap commented
ci:test:relevant

2024-07-02 23:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10876/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10876/jenkins-report.html">here</a>.</b></p>

2024-07-02 23:24 UTC, liferay-continuous-integration commented
ci:test:upgrade

Invoking upgrade test suite because an upgrade file has been modified.

2024-07-02 23:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>upgrade</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/17304/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/17304/jenkins-report.html">here</a>.</b></p>

2024-07-02 23:32 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 21 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6018936ec6dbb6d685a971a4336612219224bfd4">6018936ec6dbb6d685a971a4336612219224bfd4</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/130af8527fbd4523c0be3adc83c831bdc86b1d62">130af8527fbd4523c0be3adc83c831bdc86b1d62</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/29488045">EE Development Acceptance (master) - 636 - 2024-07-02[04:38:30]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10876/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10876/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10876/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>     [exec] &gt; Task :apps:commerce:commerce-taglib:compileJava FAILED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-taglib/src/main/java/com/liferay/commerce/taglib/servlet/taglib/TierPriceTag.java:65: error: cannot access com.liferay.petra.sql.dsl.query.sort.OrderByInfo
     [exec]               getCommerceTierPriceEntries(
     [exec]                                          ^
     [exec]   class file for com.liferay.petra.sql.dsl.query.sort.OrderByInfo not found
     [exec] 1 error
     [exec] 
     [exec] &gt; Task :apps:commerce:commerce-frontend-js:autoUpdateXml SKIPPED
     [exec] &gt; Task :apps:commerce:commerce-product-type-grouped-service:autoUpdateXml SKIPPED
     [exec] &gt; Task :apps:commerce:commerce-frontend-taglib:compileJava FROM-CACHE
     [exec] &gt; Task :apps:commerce:commerce-report-impl:compileJava FROM-CACHE
     [exec] 
     [exec] &gt; Task :apps:commerce:commerce-product-service:compileJava
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] Gradle build finished at 2024-07-02 23:30:40.776.
     [exec] 1547 actionable tasks: 1045 executed, 455 from cache, 47 up-to-date
     [exec] WARNING: The following functionality has been deprecated and will be removed in the next major release of the Develocity Gradle plugin. Run with '-Ddevelocity.deprecation.captureOrigin=true' to see where the deprecated functionality is being used. For assistance with migration, see https://gradle.com/help/gradle-plugin-develocity-migration.
     [exec] - The deprecated "gradleEnterprise.buildScan.tag" API has been replaced by "develocity.buildScan.tag"
     [exec] - The deprecated "gradleEnterprise.buildScan.buildFinished" API has been replaced by "develocity.buildScan.buildFinished"
     [exec] - The deprecated "gradleEnterprise.buildScan.background" API has been replaced by "develocity.buildScan.background"
     [exec] - The deprecated "gradleEnterprise.buildCache" API has been replaced by "develocity.buildCache"
     [exec] - The deprecated "gradleEnterprise.buildScan.value" API has been replaced by "develocity.buildScan.value"
     [exec] - The deprecated "gradleEnterprise.buildScan.link" API has been replaced by "develocity.buildScan.link"</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-38/jobs/test-portal-acceptance-pullrequest(master)/builds/10876/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-38/jobs/test-portal-acceptance-pullrequest(master)/builds/10876/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-38/jobs/test-portal-acceptance-pullrequest(master)/builds/10876/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2024-07-02 23:36 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:upgrade - 0 out of 1 jobs passed in 12 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6018936ec6dbb6d685a971a4336612219224bfd4">6018936ec6dbb6d685a971a4336612219224bfd4</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/130af8527fbd4523c0be3adc83c831bdc86b1d62">130af8527fbd4523c0be3adc83c831bdc86b1d62</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/29488045">EE Development Acceptance (master) - 636 - 2024-07-02[04:38:30]</a></p><details><summary><strong>ci:test:upgrade - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/17304/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/17304/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/17304/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>     [exec] &gt; Task :apps:commerce:commerce-taglib:compileJava FAILED
     [exec] 
     [exec] &gt; Task :apps:commerce:commerce-shipping-engine-fixed-service:jar
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-taglib/src/main/java/com/liferay/commerce/taglib/servlet/taglib/TierPriceTag.java:65: error: cannot access com.liferay.petra.sql.dsl.query.sort.OrderByInfo
     [exec]               getCommerceTierPriceEntries(
     [exec]                                          ^
     [exec]   class file for com.liferay.petra.sql.dsl.query.sort.OrderByInfo not found
     [exec] 1 error
     [exec] &gt; Task :apps:commerce:commerce-term-api:autoUpdateXml SKIPPED
     [exec] &gt; Task :apps:commerce:commerce-shipping-engine-fixed-service:autoUpdateXml SKIPPED
     [exec] &gt; Task :apps:commerce:headless:headless-commerce:headless-commerce-[REDACTED]-order-api:autoUpdateXml SKIPPED
     [exec] &gt; Task :apps:commerce:commerce-shop-by-diagram-service:autoUpdateXml SKIPPED
     [exec] &gt; Task :apps:commerce:commerce-frontend-taglib:compileJava FROM-CACHE
     [exec] &gt; Task :apps:commerce:commerce-report-impl:compileJava FROM-CACHE
     [exec] Gradle build finished at 2024-07-02 23:35:51.712.
     [exec] 
     [exec] 1556 actionable tasks: 1053 executed, 456 from cache, 47 up-to-date
     [exec] WARNING: The following functionality has been deprecated and will be removed in the next major release of the Develocity Gradle plugin. Run with '-Ddevelocity.deprecation.captureOrigin=true' to see where the deprecated functionality is being used. For assistance with migration, see https://gradle.com/help/gradle-plugin-develocity-migration.
     [exec] - The deprecated "gradleEnterprise.buildScan.tag" API has been replaced by "develocity.buildScan.tag"
     [exec] - The deprecated "gradleEnterprise.buildScan.buildFinished" API has been replaced by "develocity.buildScan.buildFinished"
     [exec] - The deprecated "gradleEnterprise.buildScan.background" API has been replaced by "develocity.buildScan.background"
     [exec] - The deprecated "gradleEnterprise.buildCache" API has been replaced by "develocity.buildCache"
     [exec] - The deprecated "gradleEnterprise.buildScan.value" API has been replaced by "develocity.buildScan.value"
     [exec] - The deprecated "gradleEnterprise.buildScan.link" API has been replaced by "develocity.buildScan.link"
     [exec] - The deprecated "gradleEnterprise.server" API has been replaced by "develocity.server"
     [exec] </pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-37/jobs/test-portal-acceptance-pullrequest(master)/builds/17304/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-37/jobs/test-portal-acceptance-pullrequest(master)/builds/17304/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-37/jobs/test-portal-acceptance-pullrequest(master)/builds/17304/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2024-07-02 23:38 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10876/">test-portal-acceptance-pullrequest(master)#10876</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10876/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-core-infra/liferay-portal/pull/7210">liferay-core-infra#7210</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/29826096">[master] ci:test:relevant - Valmir-unicap &gt; liferay-core-infra - PR#7210 - 2024-07-02[16:10:58]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>29826096<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/22443/">publish-testray-report#22443</a><br/></div></div>

2024-07-02 23:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/17304/">test-portal-acceptance-pullrequest(master)#17304</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/17304/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>upgrade<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-core-infra/liferay-portal/pull/7210">liferay-core-infra#7210</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/29831775">[master] ci:test:upgrade - Valmir-unicap &gt; liferay-core-infra - PR#7210 - 2024-07-02[16:24:25]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>29831775<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/37267/">publish-testray-report#37267</a><br/></div></div>

2024-07-03 07:33 UTC, dantewang requested changes

2024-07-03 07:33 UTC, dantewang commented on modules/util/source-formatter/src/main/resources/dependencies/replacements.json
> +		"issueKey": "LPD 28067",
@Valmir-unicap The issue key here should have a `-` e.g. `LPD-28067`.

2024-07-03 07:35 UTC, dantewang requested changes

2024-07-03 07:35 UTC, dantewang commented on modules/util/source-formatter/src/test/resources/com/liferay/source/formatter/dependencies/expected/upgrade/UpgradeCatchAllCheck.testjava
> +        CommerceTierPriceEntryMinQuantityComparator.getInstance(false);
@Valmir-unicap several wrong spacing in these lines, we need to use tabs not spaces.

2024-07-03 07:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9559/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9559/jenkins-report.html">here</a>.</b></p>

2024-07-03 07:42 UTC, dantewang commented
@Valmir-unicap Looks good, please just fix the SF issues.

2024-07-03 07:51 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 16 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6cf9174dde08911edaf7d009a1d742b0c2f200f5">6cf9174dde08911edaf7d009a1d742b0c2f200f5</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6018936ec6dbb6d685a971a4336612219224bfd4">6018936ec6dbb6d685a971a4336612219224bfd4</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/30009722">EE Development Acceptance (master) - 639 - 2024-07-02[16:39:53]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9559/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9559/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9559/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>     [exec] &gt; Task :apps:commerce:commerce-taglib:compileJava FAILED
     [exec] 
     [exec] &gt; Task :apps:commerce:commerce-frontend-taglib:jar
     [exec] &gt; Task :apps:commerce:commerce-frontend-js:autoUpdateXml SKIPPED
     [exec] &gt; Task :apps:commerce:commerce-frontend-taglib:autoUpdateXml SKIPPED
     [exec] &gt; Task :apps:commerce:commerce-image-service:autoUpdateXml SKIPPED
     [exec] &gt; Task :apps:commerce:commerce-product-measurement-unit-web:autoUpdateXml SKIPPED
     [exec] &gt; Task :apps:commerce:commerce-product-service:compileJava FROM-CACHE
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 
     [exec] &gt; Task :apps:commerce:commerce-discount-service:compileJava
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:commerce:commerce-taglib:compileJava'.
     [exec] &gt; Compilation failed; see the compiler error output for details.
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info option to get more log output.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:commerce-taglib:compileJava'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:148)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:134)
     [exec]   at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
     [exec]   at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
     [exec]   at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
     [exec]   at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-30/jobs/test-portal-acceptance-pullrequest(master)/builds/9559/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-30/jobs/test-portal-acceptance-pullrequest(master)/builds/9559/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-30/jobs/test-portal-acceptance-pullrequest(master)/builds/9559/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2024-07-03 07:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9559/">test-portal-acceptance-pullrequest(master)#9559</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9559/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-core-infra/liferay-portal/pull/7210">liferay-core-infra#7210</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/30089917">[master] ci:test:relevant - Valmir-unicap &gt; liferay-core-infra - PR#7210 - 2024-07-03[00:35:38]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>30089917<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/22804/">publish-testray-report#22804</a><br/></div></div>

2024-07-03 08:35 UTC, dantewang commented
@Valmir-unicap By the way the compile error seems relevant:

```
     [exec] > Task :apps:commerce:commerce-frontend-taglib:compileJava FROM-CACHE
     [exec] > Task :apps:commerce:commerce-frontend-taglib:copyLibs SKIPPED
     [exec] > Task :apps:commerce:commerce-frontend-taglib:classes
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-taglib/src/main/java/com/liferay/commerce/taglib/servlet/taglib/TierPriceTag.java:65: error: cannot access com.liferay.petra.sql.dsl.query.sort.OrderByInfo
     [exec] 							getCommerceTierPriceEntries(
     [exec] 							                           ^
     [exec]   class file for com.liferay.petra.sql.dsl.query.sort.OrderByInfo not found
     [exec] 1 error
     [exec] 
     [exec] > Task :apps:commerce:commerce-taglib:compileJava FAILED
```

Please resend.

2024-07-03 08:35 UTC, closed without merging

2024-07-03 17:10 UTC, Valmir-unicap commented
Thanks @dantewang!  I'm going to fix it!