[TS] LPS-154862 Unable to manage a site without the user locale enabled
liferay-core-infra/liferay-portal pull request #961
Opened 2022-06-15 08:23 UTC by joseluisbango

Relevant issues: 

- https://issues.liferay.com/browse/LPS-154862
- https://issues.liferay.com/browse/PTR-3085

---

Hi @liferay-core-infra,

Could you review this pull?

As we discussed in PTR-3085 with Lima and Echo teams, users should be able to manage a Site using any language as long as it is available in the instance. Currently, they can only do that if they go to Site Admin from _Control Panel > Sites_. If they navigate to Site Admin from a different place, such us the Site Selector shown when clicking the compass icon (what they usually do), they cannot change the display language.

They were able to do this in 6.2 manually adding the language code to the URL, so they perceive that as loss of functionality.

I have added a property as requested in the PTR so that the users can see the Site Admin pages (`/~/control_panel` pages) in any instance-available language. In addition, I have changed the `user_locale_options.jsp` to allow the users to easily change to their language.

Let me know if you have any questions.

Thanks!

2022-06-15 08:23 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2022-06-15 08:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/1768/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1768/jenkins-report.html">here</a>.</b></p>

2022-06-15 08:28 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3b33e0a69dbd6e3502bbe0dd7a11e4946ee84b52">3b33e0a69dbd6e3502bbe0dd7a11e4946ee84b52</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joseluisbango/liferay-portal/tree/LPS-154862_master">LPS-154862_master</a><br/>Branch GIT ID: <a href="https://github.com/joseluisbango/liferay-portal/commit/149bf40509020ba8121d819e70d89f8b94f0bab3">149bf40509020ba8121d819e70d89f8b94f0bab3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/1768/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1768/jenkins-report.html">here</a>.</h5></details></html>

2022-06-15 08:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/1768/">test-portal-source-format#1768</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1768/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-core-infra/liferay-portal/pull/961">liferay-core-infra#961</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1878928541">[master] ci:test:sf - joseluisbango &gt; liferay-core-infra - PR#961 - 2022-06-15[01:23:40]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/6737/">publish-testray-report#6737</a><br/></div></div>

2022-06-15 08:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/3287/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3287/jenkins-report.html">here</a>.</b></p>

2022-06-15 08:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>acceptance</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/1409/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1409/jenkins-report.html">here</a>.</b></p>

2022-06-15 10:39 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 27 out of 27 jobs passed</h3><h3>:x: ci:test:relevant - 235 out of 244 jobs passed in 1 hour 52 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/3406">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1297401_3287</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3b33e0a69dbd6e3502bbe0dd7a11e4946ee84b52">3b33e0a69dbd6e3502bbe0dd7a11e4946ee84b52</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d8ad49e8b7f162a4882b5054b9ea4ddcae3289db">d8ad49e8b7f162a4882b5054b9ea4ddcae3289db</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3405">Acceptance Upstream DXP (master) #3405</a></p><details><summary><strong>ci:test:stable - 27 out of 27 jobs PASSED</strong></summary><details><summary><strong>27 Successful Jobs:</strong></summary><ul><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/29629/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/26844/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/60475/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/62562/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/60483/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/28307/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/24520/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/67676/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/62572/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/56226/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/60484/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/36839/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/23091/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/27852/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/64724/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/27645/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/28361/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/64726/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/36826/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/55666/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/62550/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/64748/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/27093/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/36823/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/24999/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/23083/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/27903/">unit-jdk8_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 235 out of 244 jobs PASSED</strong></summary><div><h4>9 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/3287/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/63610/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/47515/"><strike>functional-tomcat90-mysql57-jdk8/0/11</strike></a></li></ul></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/60491/"><strike>modules-integration-mysql57-jdk8/0/4</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53968/"><strike>modules-integration-mysql57-jdk8/0/7</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53966/"><strike>modules-integration-mysql57-jdk8/0/10</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/62573/"><strike>modules-integration-mysql57-jdk8/0/11</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/60485/"><strike>modules-integration-mysql57-jdk8/0/12</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/60487/"><strike>modules-integration-mysql57-jdk8/0/14</strike></a></li></ul></li></ul></div><details><summary><strong>235 Successful Jobs:</strong></summary><ul><li>central-requirements-jdk8<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/23415/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/ [...]

2022-06-15 10:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/3287/">test-portal-acceptance-pullrequest(master)#3287</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3287/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-core-infra/liferay-portal/pull/961">liferay-core-infra#961</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1878992640">[master] ci:test:relevant - joseluisbango &gt; liferay-core-infra - PR#961 - 2022-06-15[01:47:17]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/8915/">publish-testray-report#8915</a><br/></div></div>

2022-06-15 11:26 UTC, dantewang commented
@joseluisbango I'll look into this one tomorrow, but I'm a bit confused by the message of this commit: https://github.com/liferay-core-infra/liferay-portal/pull/961/commits/4ce728c0bd0c97ac9a3fabecac7a40ad7203f3f4.

Does master need it, or is this only for 7.2.x? For the former, please modify the message; for the latter, please exclude the commit.

2022-06-15 13:26 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:acceptance - 1191 out of 1266 jobs passed in 4 hours 38 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3b33e0a69dbd6e3502bbe0dd7a11e4946ee84b52">3b33e0a69dbd6e3502bbe0dd7a11e4946ee84b52</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3b33e0a69dbd6e3502bbe0dd7a11e4946ee84b52">3b33e0a69dbd6e3502bbe0dd7a11e4946ee84b52</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3406">Acceptance Upstream DXP (master) #3406</a></p><details><summary><strong>ci:test:acceptance - 1191 out of 1266 jobs PASSED</strong></summary><div><h4>75 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/1409/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>archived-module-smoke-jdk8<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/29688/"><strike>archived-module-smoke-jdk8/0/0</strike></a></li></ul></li><li>archived-modules-test-jdk8<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/24378/"><strike>archived-modules-test-jdk8/0/0</strike></a></li></ul></li><li>functional-tomcat90-db2111-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/62604/"><strike>functional-tomcat90-db2111-jdk8/0/3</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/64785/"><strike>functional-tomcat90-db2111-jdk8/0/4</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/67708/"><strike>functional-tomcat90-db2111-jdk8/0/7</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/63743/"><strike>functional-tomcat90-db2111-jdk8/0/14</strike></a></li></ul></li><li>functional-tomcat90-mariadb104-jdk8<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/27872/"><strike>functional-tomcat90-mariadb104-jdk8/2/3</strike></a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/27796/"><strike>functional-tomcat90-mysql57-jdk8/3/12</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/60552/"><strike>functional-tomcat90-mysql57-jdk8/6/10</strike></a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/27112/"><strike>functional-tomcat90-mysql57-jdk8/7/17</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/64797/"><strike>functional-tomcat90-mysql57-jdk8/7/18</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/56202/"><strike>functional-tomcat90-mysql57-jdk8/14/4</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/55778/"><strike>functional-tomcat90-mysql57-jdk8/19/15</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/47604/"><strike>functional-tomcat90-mysql57-jdk8/20/17</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/62665/"><strike>functional-tomcat90-mysql57-jdk8/20/18</strike></a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/27927/"><strike>functional-tomcat90-mysql57-jdk8/20/22</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/65723/"><strike>functional-tomcat90-mysql57-jdk8/25/3</strike></a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/21555/"><strike>functional-tomcat90-mysql57-jdk8/27/16</strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/25044/"><strike>functional-tomcat90-mysql57-jdk8/33/5</strike></a></li></ul></li><li>functional-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/65795/"><strike>functional-tomcat90-oracle193-jdk8/2/0</strike></a></li></ul></li><li>functional-tomcat90-postgresql134-jdk8<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/28342/"><strike>functional-tomcat90-postgresql134-jdk8/2/2</strike></a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/28420/"><strike>functional-tomcat90-postgresql134-jdk8/2/3</strike></a></li></ul></li><li>functional-tomcat90-sqlserver2017-jdk8<ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/25688/"><strike>functional-tomcat90-sqlserver2017-jdk8/1/11</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/62672/"><strike>functional-tomcat90-sqlserver2017-jdk8/1/21</strike></a></li></ul></li><li>functional-tomcat90-sqlserver2019-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/60550/"><strike>functional-tomcat90-sqlserver2019-jdk8/1/21</strike></a></li></ul></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/65810/"><strike>modules-integration-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/65807/"><strike>modules-integration-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/64434/"><strike>modules-integration-mysql57-jdk8/0/6</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/60614/"><strike>modules-integration-mysql57-jdk8/0/8</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/60613/"><strike>modules-integration-mysql57-jdk8/0/9</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/55832/"><strike>modules-integration-mysql57-jdk8/0/17</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/63742/"><strike>modules-integration-mysql57-jdk8/1/1</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/56261/"><strike>modules-integration-mysql57-jdk8/1/2</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/63738/"><strike>modules-integration-mysql57-jdk8/1/3</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/62162/"><strike>modules-integration-mysql57-jdk8/1/4</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/67785/"><strike>modules-integration-mysql57-jdk8/1/5</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/47612/"><strike>modules-integration-mysql57-jdk8/1/9</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptan [...]

2022-06-15 14:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/1409/">test-portal-acceptance-pullrequest(master)#1409</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1409/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>acceptance<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-core-infra/liferay-portal/pull/961">liferay-core-infra#961</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1879172055">[master] ci:test:acceptance - joseluisbango &gt; liferay-core-infra - PR#961 - 2022-06-15[01:48:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/3333/">publish-testray-report#3333</a><br/></div></div>

2022-06-15 16:04 UTC, joseluisbango commented
Hey @dantewang,
I added that commit because I followed the approach used in the latest modification of that file: 
- This is the commit: https://github.com/liferay/liferay-portal/commit/11594965b60570fca9835aa8848e384d1eb942c5
- Pull https://github.com/liferay-frontend/liferay-portal/pull/570

`user_locale_options.jsp` was extracted from `portal-web` to its own module in LPS-115798 so it shouldn't be necessary to change it in master, I will remove that commit and force-push the changes.

2022-06-16 02:32 UTC, dantewang commented
@joseluisbango Thanks for the update, but sorry I get a bit confused again by your reply about how the JSP is extracted.

I would like to get clarification about:

- is the change to this file needed for your fix on master?
- if not, can this change be considered as a part of "applying the new pattern"?

2022-06-16 09:07 UTC, joseluisbango commented
Hi @dantewang. Let me clarify:

> - is the change to this file needed for your fix on master?

No, I don't think so. I think `portal-web/.../user_locale_options.jsp` is not used anymore after being extracted to `portal-user-locale-options-web`.

> - if not, can this change be considered as a part of "applying the new pattern"?

I would keep that file without any modification in master and then add an additional commit when backporting to 7.2.

Does it sound ok to you? Sorry for the confusion.

2022-06-20 05:53 UTC, dantewang requested changes
@joseluisbango 
Please modify your commit according to the comments. By the way, I want to clarify some of the behavior:

I built on this PR and started DXP, changed the admin's language to Chinese, and created a site with only English as default and available language.

- Since I didn't enable the portal property you added, I reproduced the behavior (the site is displayed as English after creating a page); however,
- after shutting down portal, changing the property to `true`, and restarting, the behavior became:
  - English was displayed when I opened localhost:8080
  - I was able to switch back to Chinese by going to Account Settings and clicking on the notification
  - However, every time I went to any of the site pages, or opening the content page editor, they are displayed as English,
  - and when I went back to control panel page of the site, I got a notification which allows me to switch back to Chinese

What I want to clarify:
- Is the behavior expected that I have to manually change the language every time after I visit a site page)?
- Is the behavior expected that the content page editor is still displayed in English?

2022-06-20 05:53 UTC, dantewang commented on modules/apps/friendly-url/friendly-url-service/src/main/java/com/liferay/friendly/url/internal/servlet/FriendlyURLServlet.java
> +					(!PortalUtil.isControlPanelPath(path) ||
@joseluisbango Please use `portal.isControlPanelPath` here. The `portal` is already a `@Reference` in this class (all its sub-classes are OSGi components).

2022-06-20 05:53 UTC, dantewang commented on modules/apps/friendly-url/friendly-url-service/src/main/java/com/liferay/friendly/url/internal/servlet/FriendlyURLServlet.java
> +					(!PortalUtil.isControlPanelPath(path) ||
Also in https://github.com/liferay-core-infra/liferay-portal/pull/961/commits/7bb6c9480ad81ffbbf19601dd57b3ee92764124a

2022-06-20 06:07 UTC, dantewang commented
@joseluisbango By the way, before resending or force pushing, please make sure you run `ant all` in your local, and commit bnd.bnd/packageinfo changes in `portal-kernel` and `portal-impl` related to what you modified if they exist. Thanks

2022-06-21 08:31 UTC, joseluisbango commented
Hi @dantewang,

Sure! It sound reasonable to me too. I have already edited my previous commits and removed the unnecessary one. 

Thanks for the review!

2022-06-21 08:32 UTC, dantewang approved these changes

2022-06-21 08:32 UTC, dantewang commented
ci:test:sf

2022-06-21 08:32 UTC, dantewang commented
ci:test:relevant

2022-06-21 08:33 UTC, dantewang commented
ci:test

2022-06-21 08:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/1831/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1831/jenkins-report.html">here</a>.</b></p>

2022-06-21 08:36 UTC, dantewang commented
@tinatian This one looks OK to me.

2022-06-21 08:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4412/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4412/jenkins-report.html">here</a>.</b></p>

2022-06-21 08:37 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2dae8872b8384a717a9a648a2753b3ad50c39f5f">2dae8872b8384a717a9a648a2753b3ad50c39f5f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joseluisbango/liferay-portal/tree/LPS-154862_master">LPS-154862_master</a><br/>Branch GIT ID: <a href="https://github.com/joseluisbango/liferay-portal/commit/8ef8db5d0ecefb50fe9b6da585acacb2219d63e0">8ef8db5d0ecefb50fe9b6da585acacb2219d63e0</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/1831/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1831/jenkins-report.html">here</a>.</h5></details></html>

2022-06-21 08:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>default</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/1825/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1825/jenkins-report.html">here</a>.</b></p>

2022-06-21 08:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/1831/">test-portal-source-format#1831</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1831/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-core-infra/liferay-portal/pull/961">liferay-core-infra#961</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1884283523">[master] ci:test:sf - joseluisbango &gt; liferay-core-infra - PR#961 - 2022-06-21[01:33:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/6986/">publish-testray-report#6986</a><br/></div></div>

2022-06-21 10:57 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 26 out of 27 jobs passed</h3><h3>:x: ci:test:relevant - 232 out of 244 jobs passed in 2 hours 21 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2dae8872b8384a717a9a648a2753b3ad50c39f5f">2dae8872b8384a717a9a648a2753b3ad50c39f5f</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2dae8872b8384a717a9a648a2753b3ad50c39f5f">2dae8872b8384a717a9a648a2753b3ad50c39f5f</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3434">Acceptance Upstream DXP (master) #3434</a></p><details><summary><strong>ci:test:stable - 26 out of 27 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/61204/"><strike>modules-integration-mysql57-jdk8_stable/0/2</strike></a></li></ul></li></ul></div><details><summary><strong>26 Successful Jobs:</strong></summary><ul><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/32273/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/76648/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/73696/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/63782/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/72986/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/32505/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/72238/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/73697/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/63785/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/70765/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/72239/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/29261/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/28534/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/76651/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/68720/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/63776/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53918/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/31555/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/74611/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/61205/">modules-integration-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/74614/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/32504/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/76632/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/26859/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/70760/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/26921/">unit-jdk8_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 232 out of 244 jobs PASSED</strong></summary><div><h4>12 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4412/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/76647/"><strike>central-requirements-jdk8/0/0</strike></a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/72980/"><strike>functional-tomcat90-mysql57-jdk8/0/8</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/70763/"><strike>functional-tomcat90-mysql57-jdk8/0/19</strike></a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/24743/"><strike>functional-tomcat90-mysql57-jdk8/3/8</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/71004/"><strike>functional-tomcat90-mysql57-jdk8/5/20</strike></a></li></ul></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/72241/"><strike>modules-integration-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/64258/"><strike>modules-integration-mysql57-jdk8/0/7</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/63346/"><strike>modules-integration-mysql57-jdk8/0/10</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/71015/"><strike>modules-integration-mysql57-jdk8/0/12</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/68733/"><strike>modules-integration-mysql57-jdk8/0/13</strike></a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/61204/"><strike>modules-integration-mysql57-jdk8_stable/0/2</strike></a></li></ul></li></ul></div><details><summary><strong>232 Successful Jobs:</strong></summary>< [...]

2022-06-21 11:04 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4412/">test-portal-acceptance-pullrequest(master)#4412</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4412/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-core-infra/liferay-portal/pull/961">liferay-core-infra#961</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1884343587">[master] ci:test:relevant - joseluisbango &gt; liferay-core-infra - PR#961 - 2022-06-21[01:35:41]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/12325/">publish-testray-report#12325</a><br/></div></div>

2022-06-21 11:50 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:default - 1180 out of 1269 jobs passed in 3 hours 11 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2dae8872b8384a717a9a648a2753b3ad50c39f5f">2dae8872b8384a717a9a648a2753b3ad50c39f5f</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2dae8872b8384a717a9a648a2753b3ad50c39f5f">2dae8872b8384a717a9a648a2753b3ad50c39f5f</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3434">Acceptance Upstream DXP (master) #3434</a></p><details><summary><strong>ci:test:default - 1180 out of 1269 jobs PASSED</strong></summary><div><h4>89 Failed Jobs:</h4><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/1825/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>archived-module-smoke-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/76707/"><strike>archived-module-smoke-jdk8/0/0</strike></a></li></ul></li><li>archived-modules-test-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/64302/"><strike>archived-modules-test-jdk8/0/0</strike></a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/72282/"><strike>central-requirements-jdk8/0/0</strike></a></li></ul></li><li>functional-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/63838/"><strike>functional-tomcat90-hypersonic20-jdk8/0/0</strike></a></li></ul></li><li>functional-tomcat90-mariadb102-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/73747/"><strike>functional-tomcat90-mariadb102-jdk8/0/0</strike></a></li></ul></li><li>functional-tomcat90-mariadb104-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/61222/"><strike>functional-tomcat90-mariadb104-jdk8/0/0</strike></a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/72258/"><strike>functional-tomcat90-mysql57-jdk8/1/5</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/72290/"><strike>functional-tomcat90-mysql57-jdk8/2/5</strike></a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/26954/"><strike>functional-tomcat90-mysql57-jdk8/3/12</strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/29422/"><strike>functional-tomcat90-mysql57-jdk8/4/14</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/61244/"><strike>functional-tomcat90-mysql57-jdk8/8/18</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53962/"><strike>functional-tomcat90-mysql57-jdk8/8/20</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/64360/"><strike>functional-tomcat90-mysql57-jdk8/10/16</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/72257/"><strike>functional-tomcat90-mysql57-jdk8/10/21</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/73711/"><strike>functional-tomcat90-mysql57-jdk8/10/24</strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/31581/"><strike>functional-tomcat90-mysql57-jdk8/19/10</strike></a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/28597/"><strike>functional-tomcat90-mysql57-jdk8/19/17</strike></a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/29279/"><strike>functional-tomcat90-mysql57-jdk8/20/19</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/68744/"><strike>functional-tomcat90-mysql57-jdk8/20/20</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/61224/"><strike>functional-tomcat90-mysql57-jdk8/20/24</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/41226/"><strike>functional-tomcat90-mysql57-jdk8/21/24</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/70777/"><strike>functional-tomcat90-mysql57-jdk8/22/13</strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/28558/"><strike>functional-tomcat90-mysql57-jdk8/23/12</strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/28646/"><strike>functional-tomcat90-mysql57-jdk8/24/9</strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/31571/"><strike>functional-tomcat90-mysql57-jdk8/24/21</strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/31574/"><strike>functional-tomcat90-mysql57-jdk8/25/5</strike></a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/23097/"><strike>functional-tomcat90-mysql57-jdk8/30/6</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/73730/"><strike>functional-tomcat90-mysql57-jdk8/30/19</strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/30964/"><strike>functional-tomcat90-mysql57-jdk8/30/24</strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/29427/"><strike>functional-tomcat90-mysql57-jdk8/31/0</strike></a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/24771/"><strike>functional-tomcat90-mysql57-jdk8/31/21</strike></a></li></ul></li><li>functional-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/72298/"><strike>functional-tomcat90-oracle193-jdk8/0/0</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/63394/"><strike>functional-tomcat90-oracle193-jdk8/1/24</strike></a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/29289/"><strike>functional-tomcat90-oracle193-jdk8/2/0</strike></a></li></ul></li><li>functional-tomcat90-postgresql134-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/76700/"><strike>functional-tomcat90-postgresql134-jdk8/0/0</strike></a></li></ul></li><li>functional-tomcat90-sqlserver2017-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53955/"><strike>functional-tomcat90-sqlserver2017-jdk8/0/0</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/76682/"><strike>functional-tomcat90-sqlserver2017-jdk8/1/11</strike></a></li></ul></li><li>functional-tomcat90-sqlserver2019-jdk8<ul><li><a [...]

2022-06-21 12:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/1825/">test-portal-acceptance-pullrequest(master)#1825</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1825/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>default<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-core-infra/liferay-portal/pull/961">liferay-core-infra#961</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1884372263">[master] ci:test:default - joseluisbango &gt; liferay-core-infra - PR#961 - 2022-06-21[01:37:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/4520/">publish-testray-report#4520</a><br/></div></div>

2022-06-22 06:01 UTC, zhangyan0701 commented
No regressions found.

2022-06-24 20:30 UTC, tinatian commented
@joseluisbango This is related to the behavior of user, I believe this is in the user&system team scope, could you please send pull to them to verify? I am going to close this pull, please feel free to reopen if user&system team does not take it.

Thanks.
Tina

2022-06-24 20:30 UTC, closed without merging

2022-06-24 20:31 UTC, tinatian commented
@joseluisbango Also, please add test to cover your changes.

Thanks.
Tina.